<a href="https://colab.research.google.com/github/Mercymerine/Pandas-Analysis/blob/main/us_baby_names.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [37]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [38]:
url = ('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')
baby_names = pd.read_csv(url, sep = ',', index_col=0)
baby_names.head()

          Id     Name  Year Gender State  Count
11349  11350     Emma  2004      F    AK     62
11350  11351  Madison  2004      F    AK     48
11351  11352   Hannah  2004      F    AK     46
11352  11353    Grace  2004      F    AK     44
11353  11354    Emily  2004      F    AK     41

### Step 4. See the first 10 entries

In [39]:
baby_names.head(10)

          Id      Name  Year Gender State  Count
11349  11350      Emma  2004      F    AK     62
11350  11351   Madison  2004      F    AK     48
11351  11352    Hannah  2004      F    AK     46
11352  11353     Grace  2004      F    AK     44
11353  11354     Emily  2004      F    AK     41
11354  11355   Abigail  2004      F    AK     37
11355  11356    Olivia  2004      F    AK     33
11356  11357  Isabella  2004      F    AK     30
11357  11358    Alyssa  2004      F    AK     29
11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [40]:
baby_names.shape

(1016395, 6)

In [41]:
baby_names.head()

          Id     Name  Year Gender State  Count
11349  11350     Emma  2004      F    AK     62
11350  11351  Madison  2004      F    AK     48
11351  11352   Hannah  2004      F    AK     46
11352  11353    Grace  2004      F    AK     44
11353  11354    Emily  2004      F    AK     41

In [46]:
#??????????? 'Unnamed: 0'

'Name'

In [68]:
#baby_names = baby_names.drop(columns=['Id'], axis=1)
print(baby_names)

            Name  Year Gender State  Count
11349       Emma  2004      F    AK     62
11350    Madison  2004      F    AK     48
11351     Hannah  2004      F    AK     46
11352      Grace  2004      F    AK     44
11353      Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
5647421     Seth  2014      M    WY      5
5647422  Spencer  2014      M    WY      5
5647423     Tyce  2014      M    WY      5
5647424   Victor  2014      M    WY      5
5647425   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. Is there more male or female names in the dataset?

In [70]:
gender_counts = baby_names['Gender'].value_counts()
print(gender_counts)

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [48]:
baby_names.head()

          Name  Year Gender State  Count
11349     Emma  2004      F    AK     62
11350  Madison  2004      F    AK     48
11351   Hannah  2004      F    AK     46
11352    Grace  2004      F    AK     44
11353    Emily  2004      F    AK     41

In [49]:
names = baby_names.groupby('Name')
print(names)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x78ef1095af50>

### Step 8. How many different names exist in the dataset?

In [51]:
num_names = len(names.groups)
print(num_names)

17632

### Step 9. What is the name with most occurrences?

In [56]:
most_common_name = names.size().idxmax()
print(most_common_name)

Riley

### Step 10. How many different names have the least occurrences?

In [63]:
min_occurence = names.size().min()
print(min_occurence)
names_with_min_occurence = (names.size() == min_occurence).sum()
print(names_with_min_occurence)

1
3682

### Step 11. What is the median name occurrence?

In [64]:
name_occurences = names.size()
median_occurrence = name_occurences.median()
print(median_occurrence)

8.0

### Step 12. What is the standard deviation of names?

In [66]:
name_occurences = names.size()
#print(name_occurences)
std = name_occurences.std()
print(std)

122.0299635081389

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [ ]:
#?????????/

In [71]:
names.head()

            Name  Year Gender State  Count
11349       Emma  2004      F    AK     62
11350    Madison  2004      F    AK     48
11351     Hannah  2004      F    AK     46
11352      Grace  2004      F    AK     44
11353      Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
5546649  Gryffin  2014      M    WI      5
5546676     Kroy  2014      M    WI      5
5546699     Owyn  2014      M    WI      5
5583654   Haylea  2005      F    WV      5
5619693  Coalton  2012      M    WV      7

[65502 rows x 5 columns]

In [67]:
print(names.describe())

          Year                                                           \
         count         mean       std     min      25%     50%      75%
Name
Aaban      2.0  2013.500000  0.707107  2013.0  2013.25  2013.5  2013.75
Aadan      4.0  2009.750000  2.872281  2008.0  2008.00  2008.5  2010.25
Aadarsh    1.0  2009.000000       NaN  2009.0  2009.00  2009.0  2009.00
Aaden    196.0  2010.015306  2.044322  2005.0  2008.00  2010.0  2011.00
Aadhav     1.0  2014.000000       NaN  2014.0  2014.00  2014.0  2014.00
...        ...          ...       ...     ...      ...     ...      ...
Zyra       7.0  2012.142857  2.115701  2008.0  2011.50  2013.0  2013.50
Zyrah      2.0  2012.000000  1.414214  2011.0  2011.50  2012.0  2012.50
Zyren      1.0  2013.000000       NaN  2013.0  2013.00  2013.0  2013.00
Zyria     10.0  2008.900000  2.685351  2005.0  2007.25  2008.0  2010.50
Zyriah     9.0  2009.666667  2.915476  2006.0  2007.00  2009.0  2012.00

                 Count
            max  count       mean        std  min   25%   50%    75%    max
Name
Aaban    2014.0    2.0   6.000000   0.000000  6.0  6.00   6.0   6.00    6.0
Aadan    2014.0    4.0   5.750000   0.957427  5.0  5.00   5.5   6.25    7.0
Aadarsh  2009.0    1.0   5.000000        NaN  5.0  5.00   5.0   5.00    5.0
Aaden    2014.0  196.0  17.479592  21.154974  5.0  6.00  10.0  20.00  158.0
Aadhav   2014.0    1.0   6.000000        NaN  6.0  6.00   6.0   6.00    6.0
...         ...    ...        ...        ...  ...   ...   ...    ...    ...
Zyra     2014.0    7.0   6.000000   1.154701  5.0  5.00   6.0   6.50    8.0
Zyrah    2013.0    2.0   5.500000   0.707107  5.0  5.25   5.5   5.75    6.0
Zyren    2013.0    1.0   6.000000        NaN  6.0  6.00   6.0   6.00    6.0
Zyria    2014.0   10.0   5.900000   0.737865  5.0  5.25   6.0   6.00    7.0
Zyriah   2014.0    9.0   6.444444   1.666667  5.0  5.00   6.0   7.00   10.0

[17632 rows x 16 columns]